### ISSUE TITLE
Preprint of the paper

### ISSUE THREAD

**Issue by SaiKeshav** [kelvin-jiang/FreebaseQA#1]
(My apologies for this not being a real github issue, but rather a paper-request)

Thanks a lot for sharing this awesome resource! I am really looking forward to reading the associated paper. Is there any plan to make a preprint available online? Or do we have to wait till NAACL releases the conference proceedings (in June)?  

Thanks,
Keshav

**Comment by kelvin-jiang** [comment]
Hi there,

Thanks for the interest! We're still in the middle of revising the paper for NAACL. I will email you a copy of the paper once we have finalized it.

Kelvin

**Comment by SaiKeshav** [comment]
Thanks a lot! Looking forward to it.
